# Generated by Django 6.0.7 on 2026-08-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_sharednote_uniq_shared_note_per_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('accent', models.CharField(default='#1a56db', max_length=7)),
                ('logo_ext', models.CharField(blank=True, default='', max_length=5)),
                ('logo_align', models.CharField(choices=[('left', 'Izquierda'), ('right', 'Derecha')], default='left', max_length=5)),
                ('logo_height', models.PositiveSmallIntegerField(default=10)),
                ('header_text', models.CharField(blank=True, default='', max_length=120)),
                ('footer_text', models.CharField(blank=True, default='', max_length=160)),
                ('cover', models.BooleanField(default=False)),
                ('watermark', models.BooleanField(default=False)),
                ('dark', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
    ]
