# Generated by Django 6.0.7 on 2026-08-03 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_pdfbrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('html', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PdfThemeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('ext', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='notes.pdftheme')),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.DeleteModel(
            name='PdfBrand',
        ),
        migrations.AddConstraint(
            model_name='pdfthemeimage',
            constraint=models.UniqueConstraint(fields=('theme', 'name'), name='uniq_theme_image_name'),
        ),
    ]
