# Generated by Django 6.0.7 on 2026-08-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_pdftheme_pdfthemeimage_delete_pdfbrand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteToken',
            fields=[
                ('token', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('path', models.CharField(db_index=True, max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
