# Generated by Django 6.1 on 2026-09-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_notetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharednote',
            name='can_write',
            field=models.BooleanField(default=False),
        ),
    ]
