# Generated by Django 6.1 on 2026-09-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_sharednote_can_write'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoteToken',
        ),
    ]
