# Generated by Django 6.0.7 on 2026-07-25 12:30

from django.db import migrations, models


def make_existing_users_owners(apps, schema_editor):
    """Las cuentas que ya existían son del dueño del sitio.

    El default del campo es `viewer` (lo prudente para un alta nueva), pero
    aplicado tal cual dejaría al propietario sin permiso de escritura en su
    propia bóveda: todo lo anterior a esta migración es suyo.

    Limitación conocida: si en el momento de aplicarse esta migración ya
    había cuentas invitadas además de la del propietario, TODAS se
    promocionan a `owner` por igual — el rol histórico (`admin`/`user` de
    `0001_initial`) ya no existe en este punto (se borró un día antes en
    `0003_remove_user_role`), así que no hay nada de lo que distinguirlas.
    El aviso de abajo lo deja visible en el log de `migrate` para cualquier
    base de datos donde esta migración corra a partir de ahora; para una que
    ya la aplicó, usa `manage.py audit_owner_roles`.
    """
    User = apps.get_model("accounts", "User")
    count = User.objects.count()
    if count > 1:
        print(
            f"\n[0005_user_role] AVISO: {count} cuentas existentes se "
            "promocionan a 'owner' por igual, sin distinguir cuál era la "
            "legítima. Revisa con 'manage.py audit_owner_roles' cuando "
            "termine la migración.\n"
        )
    User.objects.update(role="owner")


def noop(apps, schema_editor):
    """Marcha atrás: la columna entera desaparece, no hay nada que revertir."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Propietario'), ('editor', 'Lectura y escritura'), ('viewer', 'Sólo lectura')], default='viewer', max_length=10),
        ),
        migrations.RunPython(make_existing_users_owners, noop),
    ]
