# Generated by Django 6.0.7 on 2026-08-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('dark', 'Oscuro'), ('light', 'Claro'), ('dracula', 'Drácula'), ('pink', 'Rosa'), ('gold', 'Dorado'), ('dark-cristal', 'Dark Cristal')], default='dark', max_length=16),
        ),
    ]
