# Generated by Django 6.1 on 2026-09-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiKey',
        ),
    ]
