# Generated by Django 6.0.7 on 2026-07-29 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('revoked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'enlace maestro',
                'verbose_name_plural': 'enlaces maestros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('allowed_domains', models.TextField(blank=True, default='')),
                ('grant_days', models.PositiveSmallIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'bóveda pública',
            },
        ),
    ]
